-- ========================================================
-- أثر (Athar) — Supabase PostgreSQL Database Schema
-- Project Reference: ipwhnpfhevdaiogjuurq
-- Run this script directly in your Supabase SQL Editor
-- ========================================================

BEGIN;

CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "user_id" integer NOT NULL, "content_type_id" integer NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL);
CREATE TABLE "core_profile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL UNIQUE, "display_name" varchar(80) NOT NULL, "handle" varchar(40) NOT NULL UNIQUE, "avatar_initial" varchar(3) NOT NULL, "avatar_tone" varchar(30) NOT NULL, "avatar_image" text NOT NULL, "bio" varchar(160) NOT NULL, "verified" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE "core_follow" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "follower_id" integer NOT NULL, "following_id" integer NOT NULL, "created_at" timestamp with time zone NOT NULL, CONSTRAINT "unique_profile_follow" UNIQUE ("follower_id", "following_id"), CONSTRAINT "profile_cannot_follow_self" CHECK (NOT ("follower_id" = ("following_id"))));
CREATE TABLE "core_topic" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "category" varchar(80) NOT NULL, "name" varchar(120) NOT NULL UNIQUE, "rank" integer NOT NULL CHECK ("rank" >= 0));
CREATE TABLE "core_post" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "author_id" integer NULL, "author_name" varchar(80) NOT NULL, "handle" varchar(40) NOT NULL, "avatar_initial" varchar(3) NOT NULL, "avatar_tone" varchar(30) NOT NULL, "avatar_image" text NOT NULL, "body" text NOT NULL, "tags" jsonb NOT NULL, "topic_id" bigint NULL, "parent_id" bigint NULL, "published_at" timestamp with time zone NOT NULL, "published_label" varchar(40) NOT NULL, "verified" boolean NOT NULL, "likes" integer NOT NULL CHECK ("likes" >= 0), "replies" integer NOT NULL CHECK ("replies" >= 0), "reposts" integer NOT NULL CHECK ("reposts" >= 0));
CREATE TABLE "core_postlike" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "post_id" bigint NOT NULL, "created_at" timestamp with time zone NOT NULL, CONSTRAINT "unique_post_like" UNIQUE ("user_id", "post_id"));
CREATE TABLE "core_postrepost" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "post_id" bigint NOT NULL, "created_at" timestamp with time zone NOT NULL, CONSTRAINT "unique_post_repost" UNIQUE ("user_id", "post_id"));
CREATE TABLE "core_bookmark" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "post_id" bigint NOT NULL, "created_at" timestamp with time zone NOT NULL, CONSTRAINT "unique_post_bookmark" UNIQUE ("user_id", "post_id"));
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
ALTER TABLE "core_profile" ADD CONSTRAINT "core_profile_user_id_bf8ada58_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_profile_handle_3c5d6c77_like" ON "core_profile" ("handle" varchar_pattern_ops);
CREATE INDEX "core_profile_created_at_f9edbcd3" ON "core_profile" ("created_at");
ALTER TABLE "core_follow" ADD CONSTRAINT "core_follow_follower_id_695d5f81_fk_auth_user_id" FOREIGN KEY ("follower_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_follow" ADD CONSTRAINT "core_follow_following_id_e468b475_fk_auth_user_id" FOREIGN KEY ("following_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_follow_follower_id_695d5f81" ON "core_follow" ("follower_id");
CREATE INDEX "core_follow_following_id_e468b475" ON "core_follow" ("following_id");
CREATE INDEX "core_topic_name_5dead622_like" ON "core_topic" ("name" varchar_pattern_ops);
CREATE INDEX "core_topic_rank_44a6f932" ON "core_topic" ("rank");
ALTER TABLE "core_post" ADD CONSTRAINT "core_post_author_id_083b751e_fk_auth_user_id" FOREIGN KEY ("author_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_post" ADD CONSTRAINT "core_post_topic_id_4dc3e3ce_fk_core_topic_id" FOREIGN KEY ("topic_id") REFERENCES "core_topic" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_post" ADD CONSTRAINT "core_post_parent_id_f52ad6c0_fk_core_post_id" FOREIGN KEY ("parent_id") REFERENCES "core_post" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_post_author_id_083b751e" ON "core_post" ("author_id");
CREATE INDEX "core_post_topic_id_4dc3e3ce" ON "core_post" ("topic_id");
CREATE INDEX "core_post_parent_id_f52ad6c0" ON "core_post" ("parent_id");
CREATE INDEX "core_post_published_at_717e66d9" ON "core_post" ("published_at");
CREATE INDEX "post_pub_desc_idx" ON "core_post" ("published_at" DESC);
CREATE INDEX "post_parent_pub_idx" ON "core_post" ("parent_id", "published_at" DESC);
ALTER TABLE "core_postlike" ADD CONSTRAINT "core_postlike_user_id_83b4cc30_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_postlike" ADD CONSTRAINT "core_postlike_post_id_304a41d2_fk_core_post_id" FOREIGN KEY ("post_id") REFERENCES "core_post" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_postlike_user_id_83b4cc30" ON "core_postlike" ("user_id");
CREATE INDEX "core_postlike_post_id_304a41d2" ON "core_postlike" ("post_id");
ALTER TABLE "core_postrepost" ADD CONSTRAINT "core_postrepost_user_id_c16b0104_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_postrepost" ADD CONSTRAINT "core_postrepost_post_id_949ee890_fk_core_post_id" FOREIGN KEY ("post_id") REFERENCES "core_post" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_postrepost_user_id_c16b0104" ON "core_postrepost" ("user_id");
CREATE INDEX "core_postrepost_post_id_949ee890" ON "core_postrepost" ("post_id");
ALTER TABLE "core_bookmark" ADD CONSTRAINT "core_bookmark_user_id_3cf59058_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "core_bookmark" ADD CONSTRAINT "core_bookmark_post_id_70bde75f_fk_core_post_id" FOREIGN KEY ("post_id") REFERENCES "core_post" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_bookmark_user_id_3cf59058" ON "core_bookmark" ("user_id");
CREATE INDEX "core_bookmark_post_id_70bde75f" ON "core_bookmark" ("post_id");
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
-- Profile photos for databases created from an older snapshot:
ALTER TABLE "core_profile" ADD COLUMN IF NOT EXISTS "avatar_image" text NOT NULL DEFAULT '';
ALTER TABLE "core_post" ADD COLUMN IF NOT EXISTS "avatar_image" text NOT NULL DEFAULT '';

-- Migration tracking table for Django
CREATE TABLE IF NOT EXISTS "django_migrations" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "app" varchar(255) NOT NULL,
    "name" varchar(255) NOT NULL,
    "applied" timestamp with time zone DEFAULT NOW()
);

-- Record current migrations as applied
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('contenttypes', '0001_initial', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0001_initial', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('admin', '0001_initial', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('admin', '0002_logentry_remove_auto_add', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('admin', '0003_logentry_add_action_flag_choices', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('contenttypes', '0002_remove_content_type_name', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0002_alter_permission_name_max_length', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0003_alter_user_email_max_length', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0004_alter_user_username_opts', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0005_alter_user_last_login_null', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0006_require_contenttypes_0002', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0007_alter_validators_add_error_messages', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0008_alter_user_username_max_length', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0009_alter_user_last_name_max_length', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0010_alter_group_name_max_length', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0011_update_proxy_permissions', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('auth', '0012_alter_user_first_name_max_length', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('core', '0001_initial', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('core', '0002_topic_remove_post_following_post_author_post_parent_and_more', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('sessions', '0001_initial', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('core', '0003_alter_post_published_at_alter_profile_created_at_and_more', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('core', '0004_alter_post_published_at', NOW()) ON CONFLICT DO NOTHING;
INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('core', '0005_profile_avatar_image_post_avatar_image', NOW()) ON CONFLICT DO NOTHING;

COMMIT;
