# Generated by Django 5.2.17 on 2026-09-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('handle', models.CharField(max_length=40)),
                ('avatar_initial', models.CharField(default='أ', max_length=3)),
                ('avatar_tone', models.CharField(default='violet', max_length=30)),
                ('body', models.TextField(max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField()),
                ('published_label', models.CharField(default='الآن', max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('following', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('replies', models.PositiveIntegerField(default=0)),
                ('reposts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'منشور',
                'verbose_name_plural': 'منشورات',
                'ordering': ['-published_at'],
            },
        ),
    ]
