# Generated by Django 5.2.17 on 2026-09-18 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_remove_post_following_post_author_post_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='post_pub_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent', '-published_at'], name='post_parent_pub_idx'),
        ),
    ]
